# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-01 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180327_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='org/%Y/%m', verbose_name='教师头像'),
        ),
    ]
