# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-01 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teachers_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='image',
            new_name='images',
        ),
    ]
