# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180401_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/%Y/%m', verbose_name='教师头像'),
        ),
    ]
