# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-11 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20180411_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='futures',
        ),
        migrations.AddField(
            model_name='teachers',
            name='char',
            field=models.TextField(default='', max_length=200, verbose_name='教师简介'),
        ),
    ]
