# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-09 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_usercourse_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='comment',
        ),
    ]
