# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-22 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lrean_times',
            new_name='learn_times',
        ),
    ]
