# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180403_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categroy',
            field=models.CharField(default='', max_length=20, verbose_name='课程类别'),
        ),
    ]
