# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-03 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_categroy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categroy',
            field=models.CharField(default='web前端/后端', max_length=20, verbose_name='课程类别'),
        ),
    ]
