# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-06 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180403_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_nums',
            field=models.IntegerField(default=0, verbose_name='课时数'),
        ),
    ]
