# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-07 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='knowledge',
            field=models.CharField(default='暂无', max_length=50, verbose_name='老师告诉你能学什么'),
        ),
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(default='暂无', max_length=50, verbose_name='课程须知'),
        ),
    ]
