# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-09 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180408_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_res',
            field=models.FileField(default=0, upload_to='course_res', verbose_name='课程资源'),
        ),
    ]
