# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-09 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20180409_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False, verbose_name='课程ID'),
        ),
    ]
