# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-09 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20180409_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user_comment',
        ),
    ]
