# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-03 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180403_1106'),
        ('users', '0006_auto_20180325_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='参与课程'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='use_image/%Y/%m'),
        ),
    ]
