# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180403_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='参与课程'),
        ),
    ]
