# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-03 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180403_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='use_image/%Y/%m', verbose_name='头像'),
        ),
    ]
