# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-08 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180403_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='course',
        ),
    ]
