# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180407_1052'),
        ('users', '0011_remove_userprofile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='参与课程'),
        ),
    ]
