# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-15 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回'), ('update_email', '修改邮箱')], max_length=15, verbose_name='验证码类型'),
        ),
    ]
